apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-demo-client
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: otel-demo-client
        app.kubernetes.io/name: otel-demo-client
    spec:
      containers:
        - image: otel-demo:lzwtest
          imagePullPolicy: Always
          args:
            - "client"
            - "-s"
            - "http://otel-demo-server:8080"
            - "-i"
            - "5"
          env:
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),namespace=$(OTEL_K8S_NAMESPACE),node=$(OTEL_K8S_NODE_NAME),pod=$(OTEL_K8S_POD_NAME)
            #- name: OTEL_EXPORTER_OTLP_ENDPOINT
            #  value: signoz-otel-collector:32145 # grpc change to 4317 port
            - name: OTLP_ENDPOINT
              value: signoz-otel-collector:32145 # grpc change to 4317 port
            #- name: OTEL_EXPORTER_OTLP_INSECURE
            #  value: "true"
            - name: INSECURE_MODE
              value: "true"
            - name: PROTOCOL
              value: "http"
          name: otel-demo-client
          resources: { }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-demo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: otel-demo-server
        app.kubernetes.io/name: otel-demo-server
    spec:
      containers:
        - image: otel-demo:lzwtest
          imagePullPolicy: Always
          args:
            - "server"
            - "-w"
            - "http://otel-demo-worker:8081"
            - --mysql-addr=mysql:3306
            - --mysql-user-name=test
            - --mysql-password=test-paasword
            - --mysql-db-name=oteldemo
          env:
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),namespace=$(OTEL_K8S_NAMESPACE),node=$(OTEL_K8S_NODE_NAME),pod=$(OTEL_K8S_POD_NAME)
            #- name: OTEL_EXPORTER_OTLP_ENDPOINT
            #  value: signoz-otel-collector:32145 # grpc change to 4317 port
            - name: OTLP_ENDPOINT
              value: signoz-otel-collector:32145 # grpc change to 4317 port
            #- name: OTEL_EXPORTER_OTLP_INSECURE
            #  value: "true"
            - name: INSECURE_MODE
              value: "true"
            - name: PROTOCOL
              value: "http"
          name: otel-demo-server
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: { }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-demo-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: otel-demo-worker
        app.kubernetes.io/name: otel-demo-worker
    spec:
      containers:
        - image: otel-demo:lzwtest
          imagePullPolicy: Always
          args:
            - "worker"
          env:
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),namespace=$(OTEL_K8S_NAMESPACE),node=$(OTEL_K8S_NODE_NAME),pod=$(OTEL_K8S_POD_NAME)
            #- name: OTEL_EXPORTER_OTLP_ENDPOINT
            #  value: signoz-otel-collector:32145 # grpc change to 4317 port
            - name: OTLP_ENDPOINT
              value: signoz-otel-collector:32145 # grpc change to 4317 port
            #- name: OTEL_EXPORTER_OTLP_INSECURE
            #  value: "true"
            - name: INSECURE_MODE
              value: "true"
            - name: PROTOCOL
              value: "http"
          name: otel-demo-worker
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          resources: { }
