apiVersion: v1
kind: Service
metadata:
  name: otel-demo-server
  namespace: cloudnative
  labels:
    app.kubernetes.io/name: otel-demo-server
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32146
  selector:
    app.kubernetes.io/name: otel-demo-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: otel-demo-worker
  namespace: cloudnative
  labels:
    app.kubernetes.io/name: otel-demo-worker
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: otel-demo-worker
  type: ClusterIP
